print("Nume, prenume: Sinigribov Serghei")
print("Data si anul nasterii: 15.06.2004 ")
print("Starea civila: celibatar ")
print("Studii: profesionale,superioare: Lipsesc")
print("Experienta de lucru: Lipsește")
print("Competente aditionale: Abiltăți de lucru în Microsoft ofice, Sony Vegas, Audacity, petrecerea streamurilori pe Twitch ")
print("Cunoasterea limbilor:Rusă, română-excelent, franceză- suficient, engleză- începător")
print("Interese: Muzică, Jocuri video, Streaming și creare de content, câștig în internet ")
print("Adresa: N.Iorga 10")
print("Telefon de contact: 069678215")
print("E-mail: wyzard.19768@gmail.com")